version: "3"

services:

 backend:
   build:
    context: .
    dockerfile: simple-app/Dockerfile
   tty: true
   stdin_open: true
   ports:
     - 9000:$API_PORT
     - 9229:9229
     - 9230:9230
     - 9231:9231
   volumes:
    - ./simple-app:/app
   environment:
     - BACKEND_SOURCE_ROOT=$BACKEND_SOURCE_ROOT
     - API_PORT=$API_PORT
     - DB_PORT=$DB_PORT
     - DB_HOST=$DB_HOST
     - DB_NAME=$DB_NAME
     - DB_USER=$DB_USER
     - DB_PASSWORD=$DB_PASSWORD
     - JWT_SECRET=$JWT_SECRET
     - ENV_PUBLISH_API=$ENV_PUBLISH_API
     - TOKEN_EXPIRE=$TOKEN_EXPIRE
 db:
   image: postgres:13
   restart: always
   environment:
     - POSTGRES_DB=$DB_NAME
     - POSTGRES_USER=$DB_USER
     - POSTGRES_PASSWORD=$DB_PASSWORD
   ports:
     - $DB_PORT:5432
   volumes:
     - database-data:/var/lib/postgresql/data
volumes:
 database-data:
